name: vjchoir_archives
description: Vjchoir Archives
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  github_vjchoir_archives_api:
    path: packages/github_vjchoir_archives_api
  go_router: ^5.0.1
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  vjchoir_archives_api:
    path: packages/vjchoir_archives_api
  vjchoir_archives_repository:
    path: packages/vjchoir_archives_repository


dev_dependencies:
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/

flutter_gen:
  integrations:
    flutter_svg: true
