name: local_vjchoir_archives_api
description: Local Vjchoir Archives Api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  vjchoir_archives_api:
    path: ../vjchoir_archives_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
