name: vjchoir_archives_repository
description: Vjchoir Archives Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  github_vjchoir_archives_api: 
    path: ../github_vjchoir_archives_api
  local_vjchoir_archives_api: 
    path: ../local_vjchoir_archives_api
  shared_preferences: ^2.0.15
  vjchoir_archives_api: 
    path: ../vjchoir_archives_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.2
