name: vjchoir_archives_api
description: Vjchoir Archives Api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.2
dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
